# Generated by Django 3.0.3 on 2020-02-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200213_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
