# Generated by Django 3.0.3 on 2020-02-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Houseno', models.IntegerField()),
                ('Due_amount', models.IntegerField()),
                ('Month', models.CharField(max_length=255)),
                ('Fine', models.IntegerField()),
            ],
        ),
    ]
